server:
  port: 8443
  ssl: true
  ssl.key-store: /etc/letsencrypt/live/chalktool.in/keystore.p12
  ssl.key-store-password: RavenPuff
  ssl.keyStoreType: PKCS12
  ssl.keyAlias: tomcat


spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            authorization-uri: http://localhost:8443/login
            user-name-attribute: email

okta:
  oauth2:
    redirect-uri: /authorization-code/callback
    issuer: https://dev-339342.okta.com/oauth2/auskwu60vdYML6Lr8356
    client-id: 0oakwt4c0YVOpktJl356
    client-secret: dtlhEMQWG9ZgnRDVNNrOtl2FFbQnboZiigrT0PK9
    scopes:
      - openid
      - email
      - profile

